# Importing the necessary libraries

In [21]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import optuna
import os

# Loading the datasets

In [22]:
blr_df = pd.read_csv('../Data/Processed/blr_df.csv')
hyd_df = pd.read_csv('../Data/Processed/hyd_df.csv')
pune_df = pd.read_csv('../Data/Processed/pune_df.csv')

In [23]:
blr_df

,Date,DPT,AP,WS,WSD,RH,LST
0,2003-01-01,12.498648,916.589625,0.608896,327.505071,93.194473,30.939528
1,2003-01-02,12.825784,918.004624,3.006925,290.310937,93.578218,31.179113
2,2003-01-03,12.970981,918.453619,2.872020,279.921010,94.227231,33.045705
3,2003-01-04,12.445614,917.966755,2.678422,274.952584,93.297114,38.266933
4,2003-01-05,14.071074,918.579933,3.104962,275.257170,94.353249,33.185394
...,...,...,...,...,...,...,...
6553,2020-12-25,13.500707,916.151180,2.152634,261.457477,95.470006,32.118758
6554,2020-12-26,12.901577,917.194971,2.312996,253.686322,95.361429,32.068009
6555,2020-12-27,12.950693,916.302854,2.260313,252.095788,94.854902,34.539327
6556,2020-12-28,10.830827,916.237697,2.003774,254.229795,93.468912,31.310399
6557,2020-12-29,16.207934,915.751192,2.372698,272.744304,96.359538,32.945682

In [24]:
pune_df

,Date,DPT,AP,WS,WSD,RH,LST
0,2003-01-01,7.100958,941.961323,0.608896,327.505071,91.114710,34.246204
1,2003-01-02,10.484796,942.675433,3.006925,290.310937,91.934631,35.734294
2,2003-01-03,12.606104,942.881457,2.872020,279.921010,92.393007,32.590960
3,2003-01-04,12.646417,943.009227,2.678422,274.952584,92.312594,35.435619
4,2003-01-05,13.066706,943.762527,3.104962,275.257170,92.569458,34.235347
...,...,...,...,...,...,...,...
6553,2020-12-25,12.096190,941.053885,2.152634,261.457477,92.849653,33.209944
6554,2020-12-26,13.381471,942.263093,2.312996,253.686322,93.400294,31.352555
6555,2020-12-27,13.819016,941.287692,2.260313,252.095788,93.560516,33.862652
6556,2020-12-28,13.831078,940.630939,2.003774,254.229795,93.895661,32.318171
6557,2020-12-29,13.515426,940.271228,2.372698,272.744304,93.724668,34.509701

In [25]:
hyd_df

,Date,DPT,AP,WS,WSD,RH,LST
0,2003-01-01,9.801921,952.321702,2.702138,228.989644,91.137446,35.253027
1,2003-01-02,12.894156,953.896739,2.974241,287.669929,92.938629,31.660535
2,2003-01-03,16.945643,954.471306,3.015529,308.536731,96.690377,30.085849
3,2003-01-04,17.761199,954.172469,1.865083,299.395258,98.016959,30.569864
4,2003-01-05,14.281283,954.395644,2.287668,265.010524,93.245268,31.878895
...,...,...,...,...,...,...,...
6553,2020-12-25,13.330685,951.670802,2.015309,292.172202,94.673562,30.396700
6554,2020-12-26,14.027632,952.521458,1.736367,284.297801,94.788311,32.262344
6555,2020-12-27,13.223768,951.342613,1.754041,288.307250,94.039085,33.796627
6556,2020-12-28,12.504071,951.101661,2.012608,299.893708,93.248170,31.748070
6557,2020-12-29,12.890767,951.123203,2.545894,294.997468,93.764521,33.091597

# Splitting the Input and Predictor Variables

In [26]:
features = ['AP', 'DPT', 'WS', 'WSD', 'RH']
target = 'LST'

In [27]:
blr_X = blr_df[features].values
blr_y = blr_df[target].values

In [28]:
hyd_X = hyd_df[features].values
hyd_y = hyd_df[target].values

In [29]:
pune_X = pune_df[features].values
pune_y = pune_df[target].values

# Scaling the data

In [30]:
scaler = StandardScaler()

In [31]:
blr_X_scaled = scaler.fit_transform(blr_X)
hyd_X_scaled = scaler.transform(hyd_X)
pune_X_scaled = scaler.transform(pune_X)

# Splitting it into Training data and Testing Data

In [32]:
train_size = int(0.8 * len(blr_X_scaled))
blr_X_train = blr_X_scaled[:train_size]
blr_y_train = blr_y[:train_size]
blr_X_test = blr_X_scaled[train_size:]
blr_y_test = blr_y[train_size:]

In [33]:
train_size = int(0.8 * len(hyd_X_scaled))
hyd_X_train = hyd_X_scaled[:train_size]
hyd_y_train = hyd_y[:train_size]
hyd_X_test = hyd_X_scaled[train_size:]
hyd_y_test = hyd_y[train_size:]

In [34]:
train_size = int(0.8 * len(pune_X_scaled))
pune_X_train = pune_X_scaled[:train_size]
pune_y_train = pune_y[:train_size]
pune_X_test = pune_X_scaled[train_size:]
pune_y_test = pune_y[train_size:]

# Converting it into Pytorch Tensor for Further Analysis

In [35]:
blr_X_train_tensor  = torch.tensor(blr_X_train, dtype=torch.float32)
blr_y_train_tensor  = torch.tensor(blr_y_train, dtype=torch.float32).unsqueeze(1)
blr_X_test_tensor   = torch.tensor(blr_X_test, dtype=torch.float32)
blr_y_test_tensor   = torch.tensor(blr_y_test, dtype=torch.float32).unsqueeze(1)

hyd_X_train_tensor  = torch.tensor(hyd_X_train, dtype=torch.float32)
hyd_y_train_tensor  = torch.tensor(hyd_y_train, dtype=torch.float32).unsqueeze(1)
hyd_X_test_tensor   = torch.tensor(hyd_X_test, dtype=torch.float32)
hyd_y_test_tensor   = torch.tensor(hyd_y_test, dtype=torch.float32).unsqueeze(1)

pune_X_train_tensor = torch.tensor(pune_X_train, dtype=torch.float32)
pune_y_train_tensor = torch.tensor(pune_y_train, dtype=torch.float32).unsqueeze(1)
pune_X_test_tensor  = torch.tensor(pune_X_test, dtype=torch.float32)
pune_y_test_tensor  = torch.tensor(pune_y_test, dtype=torch.float32).unsqueeze(1)

# Defining the ANN Model

In [36]:
class ANN(nn.Module):
    def __init__(self, input_size, hidden_sizes, dropout_rate):
        super(ANN, self).__init__()
        layers = []
        in_features = input_size

        for hidden_size in hidden_sizes:
            layers.append(nn.Linear(in_features, hidden_size))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout_rate))
            in_features = hidden_size

        layers.append(nn.Linear(in_features, 1))
        self.network = nn.Sequential(*layers)

    def forward(self, x):
        return self.network(x)

# Training the Model with the Hyperparameter Tuning done using Optuna

In [37]:
def objective(trial, X_train_tensor, y_train_tensor, X_test_tensor, y_test_tensor):
    hidden_layer_count = trial.suggest_int("n_layers", 1, 2)
    hidden_sizes = [trial.suggest_int(f"n_units_l{i}", 50, 500) for i in range(hidden_layer_count)]
    dropout = trial.suggest_float("dropout", 0.0, 0.4)
    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)
    batch_size = trial.suggest_categorical("batch_size", [8])
    epochs = trial.suggest_int("epochs", 50, 150)

    model = ANN(input_size=X_train.shape[1], hidden_sizes=hidden_sizes, dropout_rate=dropout)
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    dataset = torch.utils.data.TensorDataset(X_train_tensor, y_train_tensor)
    loader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, shuffle=True)

    model.train()
    for epoch in range(epochs):
        for batch_X, batch_y in loader:
            optimizer.zero_grad()
            outputs = model(batch_X)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

    # Evaluate on test data
    model.eval()
    with torch.no_grad():
        predictions = model(X_test_tensor)
        mse = criterion(predictions, y_test_tensor).item()
    return mse

In [38]:
cities = {
    'Bangalore': (blr_X_train_tensor, blr_y_train_tensor, blr_X_test_tensor, blr_y_test_tensor),
    'Hyderabad': (hyd_X_train_tensor, hyd_y_train_tensor, hyd_X_test_tensor, hyd_y_test_tensor),
    'Pune': (pune_X_train_tensor, pune_y_train_tensor, pune_X_test_tensor, pune_y_test_tensor),
}

In [39]:
results = {}

In [40]:
for city, (X_train, y_train, X_test, y_test) in cities.items():
    print(f"Running Optuna for {city}...")
    study = optuna.create_study(direction="minimize")
    study.optimize(lambda trial: objective(trial, X_train, y_train, X_test, y_test), n_trials=30)
    
    best_trial = study.best_trial
    print(f"{city} Best MSE: {best_trial.value:.4f}")
    print(f"Best Parameters: {best_trial.params}\n")

    results[city] = best_trial

[I 2025-04-22 11:21:36,556] A new study created in memory with name: no-name-387752b2-73f9-4027-b591-4a4a4b8a82a2

Running Optuna for Bangalore...

[I 2025-04-22 11:21:52,549] Trial 0 finished with value: 7.570242404937744 and parameters: {'n_layers': 1, 'n_units_l0': 71, 'dropout': 0.12597039170855867, 'lr': 0.003550179718119552, 'batch_size': 8, 'epochs': 119}. Best is trial 0 with value: 7.570242404937744.
[I 2025-04-22 11:22:12,059] Trial 1 finished with value: 7.332128047943115 and parameters: {'n_layers': 2, 'n_units_l0': 380, 'n_units_l1': 363, 'dropout': 0.21999322098673055, 'lr': 0.000599224461642003, 'batch_size': 8, 'epochs': 60}. Best is trial 1 with value: 7.332128047943115.
[I 2025-04-22 11:22:25,641] Trial 2 finished with value: 7.856171607971191 and parameters: {'n_layers': 1, 'n_units_l0': 93, 'dropout': 0.12781103168376085, 'lr': 0.005193391176239543, 'batch_size': 8, 'epochs': 102}. Best is trial 1 with value: 7.332128047943115.
[I 2025-04-22 11:22:49,745] Trial 3 finished with value: 9.110514640808105 and parameters: {'n_layers': 2, 'n_units_l0': 376, 'n_units_l1': 280, 'dropout': 0.039044139196513686, 'lr': 0.00262450947066814, 'batch_size': 8, 'epochs': 81}. Best is trial 1 with value: 7.332128047943115.
[I 2025-04-22 11:23:09,534] Trial 4 finished with value: 8.657470703125 and parameters: {'n_layers': 2, 'n_units_l0': 320, 'n_units_l1': 146, 'dropout': 0.3975841412657951, 'lr': 0.0072804173142468065, 'batch_size': 8, 'epochs': 75}. Best is trial 1 with value: 7.332128047943115.
[I 2025-04-22 11:23:34,414] Trial 5 finished with value: 7.139224052429199 and parameters: {'n_layers': 2, 'n_units_l0': 400, 'n_units_l1': 175, 'dropout': 0.17405013132252034, 'lr': 0.0011864757981162946, 'batch_size': 8, 'epochs': 88}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:23:45,771] Trial 6 finished with value: 7.185854434967041 and parameters: {'n_layers': 1, 'n_units_l0': 139, 'dropout': 0.2407827807013109, 'lr': 0.0029773331259625837, 'batch_size': 8, 'epochs': 84}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:23:55,203] Trial 7 finished with value: 7.55653190612793 and parameters: {'n_layers': 1, 'n_units_l0': 273, 'dropout': 0.23249742085834404, 'lr': 0.0007651471298288283, 'batch_size': 8, 'epochs': 67}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:24:34,603] Trial 8 finished with value: 8.254220962524414 and parameters: {'n_layers': 2, 'n_units_l0': 468, 'n_units_l1': 473, 'dropout': 0.04254126537997882, 'lr': 0.004143875180293016, 'batch_size': 8, 'epochs': 98}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:24:42,049] Trial 9 finished with value: 7.625241279602051 and parameters: {'n_layers': 1, 'n_units_l0': 376, 'dropout': 0.2960248383703749, 'lr': 0.0001117712134050031, 'batch_size': 8, 'epochs': 51}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:25:27,488] Trial 10 finished with value: 7.856742858886719 and parameters: {'n_layers': 2, 'n_units_l0': 490, 'n_units_l1': 76, 'dropout': 0.13547062625293432, 'lr': 0.00028784606483873114, 'batch_size': 8, 'epochs': 141}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:25:40,332] Trial 11 finished with value: 7.781218528747559 and parameters: {'n_layers': 1, 'n_units_l0': 189, 'dropout': 0.298779582676678, 'lr': 0.0014527015711807247, 'batch_size': 8, 'epochs': 93}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:26:17,333] Trial 12 finished with value: 7.5099406242370605 and parameters: {'n_layers': 2, 'n_units_l0': 177, 'n_units_l1': 204, 'dropout': 0.2855696798020846, 'lr': 0.0016220115923761597, 'batch_size': 8, 'epochs': 117}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:26:28,937] Trial 13 finished with value: 7.842289447784424 and parameters: {'n_layers': 1, 'n_units_l0': 184, 'dropout': 0.17325974473265904, 'lr': 0.0004155302025770585, 'batch_size': 8, 'epochs': 84}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:27:01,638] Trial 14 finished with value: 7.2477006912231445 and parameters: {'n_layers': 2, 'n_units_l0': 261, 'n_units_l1': 62, 'dropout': 0.37214607473129435, 'lr': 0.0018641422703149413, 'batch_size': 8, 'epochs': 114}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:27:20,364] Trial 15 finished with value: 7.861562728881836 and parameters: {'n_layers': 1, 'n_units_l0': 135, 'dropout': 0.18417501576293765, 'lr': 0.009404921571948301, 'batch_size': 8, 'epochs': 138}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:27:38,920] Trial 16 finished with value: 7.928591728210449 and parameters: {'n_layers': 1, 'n_units_l0': 422, 'dropout': 0.2546538638333647, 'lr': 0.0010367858693980513, 'batch_size': 8, 'epochs': 90}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:28:11,891] Trial 17 finished with value: 8.294204711914062 and parameters: {'n_layers': 2, 'n_units_l0': 307, 'n_units_l1': 304, 'dropout': 0.07939887589665179, 'lr': 0.0002111378798577235, 'batch_size': 8, 'epochs': 72}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:28:27,063] Trial 18 finished with value: 7.249661445617676 and parameters: {'n_layers': 1, 'n_units_l0': 225, 'dropout': 0.34491513983436917, 'lr': 0.002445971450493088, 'batch_size': 8, 'epochs': 105}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:29:08,787] Trial 19 finished with value: 8.207778930664062 and parameters: {'n_layers': 2, 'n_units_l0': 108, 'n_units_l1': 183, 'dropout': 0.18279316501179396, 'lr': 0.0010146683276439834, 'batch_size': 8, 'epochs': 129}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:29:23,408] Trial 20 finished with value: 7.318051338195801 and parameters: {'n_layers': 1, 'n_units_l0': 443, 'dropout': 0.0024883317227469004, 'lr': 0.0005300129731979756, 'batch_size': 8, 'epochs': 63}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:29:57,755] Trial 21 finished with value: 7.5540852546691895 and parameters: {'n_layers': 2, 'n_units_l0': 280, 'n_units_l1': 51, 'dropout': 0.36603503981127894, 'lr': 0.001825622051250259, 'batch_size': 8, 'epochs': 111}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:30:46,725] Trial 22 finished with value: 7.902493953704834 and parameters: {'n_layers': 2, 'n_units_l0': 229, 'n_units_l1': 129, 'dropout': 0.3397615617843196, 'lr': 0.0027402799894121993, 'batch_size': 8, 'epochs': 150}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:31:17,383] Trial 23 finished with value: 7.569890975952148 and parameters: {'n_layers': 2, 'n_units_l0': 333, 'n_units_l1': 209, 'dropout': 0.25500011996676075, 'lr': 0.0012974057294147109, 'batch_size': 8, 'epochs': 86}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:31:52,377] Trial 24 finished with value: 7.71100378036499 and parameters: {'n_layers': 2, 'n_units_l0': 242, 'n_units_l1': 107, 'dropout': 0.15048416957954774, 'lr': 0.005499250500148652, 'batch_size': 8, 'epochs': 110}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:32:27,118] Trial 25 finished with value: 7.7692084312438965 and parameters: {'n_layers': 2, 'n_units_l0': 147, 'n_units_l1': 51, 'dropout': 0.1026742971216127, 'lr': 0.0023037012974312515, 'batch_size': 8, 'epochs': 123}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:33:01,996] Trial 26 finished with value: 7.4278950691223145 and parameters: {'n_layers': 2, 'n_units_l0': 348, 'n_units_l1': 231, 'dropout': 0.3950671792484542, 'lr': 0.0008018418058480764, 'batch_size': 8, 'epochs': 94}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:33:24,135] Trial 27 finished with value: 7.246336460113525 and parameters: {'n_layers': 2, 'n_units_l0': 50, 'n_units_l1': 148, 'dropout': 0.20585716739900273, 'lr': 0.0035999631673431414, 'batch_size': 8, 'epochs': 79}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:33:34,526] Trial 28 finished with value: 7.476278781890869 and parameters: {'n_layers': 1, 'n_units_l0': 64, 'dropout': 0.20760470533535474, 'lr': 0.004068138369656453, 'batch_size': 8, 'epochs': 78}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:33:50,769] Trial 29 finished with value: 7.877206325531006 and parameters: {'n_layers': 2, 'n_units_l0': 52, 'n_units_l1': 373, 'dropout': 0.2531761483613431, 'lr': 0.003299927006360127, 'batch_size': 8, 'epochs': 55}. Best is trial 5 with value: 7.139224052429199.
[I 2025-04-22 11:33:50,770] A new study created in memory with name: no-name-7767e73a-486f-4b77-a176-59b4a407eae5

Bangalore Best MSE: 7.1392
Best Parameters: {'n_layers': 2, 'n_units_l0': 400, 'n_units_l1': 175, 'dropout': 0.17405013132252034, 'lr': 0.0011864757981162946, 'batch_size': 8, 'epochs': 88}

Running Optuna for Hyderabad...

[I 2025-04-22 11:34:42,320] Trial 0 finished with value: 10.2513427734375 and parameters: {'n_layers': 2, 'n_units_l0': 398, 'n_units_l1': 495, 'dropout': 0.15883310067937076, 'lr': 0.004195412551561011, 'batch_size': 8, 'epochs': 100}. Best is trial 0 with value: 10.2513427734375.
[I 2025-04-22 11:35:14,376] Trial 1 finished with value: 10.119962692260742 and parameters: {'n_layers': 2, 'n_units_l0': 333, 'n_units_l1': 390, 'dropout': 0.23390798094074705, 'lr': 0.008005510913968743, 'batch_size': 8, 'epochs': 75}. Best is trial 1 with value: 10.119962692260742.
[I 2025-04-22 11:35:28,301] Trial 2 finished with value: 8.92397403717041 and parameters: {'n_layers': 1, 'n_units_l0': 236, 'dropout': 0.0424096522405379, 'lr': 0.0005845481821681345, 'batch_size': 8, 'epochs': 99}. Best is trial 2 with value: 8.92397403717041.
[I 2025-04-22 11:35:58,480] Trial 3 finished with value: 8.874987602233887 and parameters: {'n_layers': 2, 'n_units_l0': 458, 'n_units_l1': 484, 'dropout': 0.053981236102977226, 'lr': 0.0001823945594148436, 'batch_size': 8, 'epochs': 56}. Best is trial 3 with value: 8.874987602233887.
[I 2025-04-22 11:36:30,103] Trial 4 finished with value: 9.570903778076172 and parameters: {'n_layers': 2, 'n_units_l0': 481, 'n_units_l1': 377, 'dropout': 0.18355664866861465, 'lr': 0.0013877664769236064, 'batch_size': 8, 'epochs': 65}. Best is trial 3 with value: 8.874987602233887.
[I 2025-04-22 11:36:39,306] Trial 5 finished with value: 8.906105995178223 and parameters: {'n_layers': 1, 'n_units_l0': 341, 'dropout': 0.13827613516851694, 'lr': 0.001531182788713495, 'batch_size': 8, 'epochs': 63}. Best is trial 3 with value: 8.874987602233887.
[I 2025-04-22 11:36:55,138] Trial 6 finished with value: 9.216914176940918 and parameters: {'n_layers': 1, 'n_units_l0': 183, 'dropout': 0.36828558156722074, 'lr': 0.0009765363400389618, 'batch_size': 8, 'epochs': 116}. Best is trial 3 with value: 8.874987602233887.
[I 2025-04-22 11:37:14,314] Trial 7 finished with value: 9.379952430725098 and parameters: {'n_layers': 1, 'n_units_l0': 65, 'dropout': 0.15397920990614083, 'lr': 0.00030986060452901253, 'batch_size': 8, 'epochs': 146}. Best is trial 3 with value: 8.874987602233887.
[I 2025-04-22 11:38:21,422] Trial 8 finished with value: 9.019716262817383 and parameters: {'n_layers': 2, 'n_units_l0': 379, 'n_units_l1': 482, 'dropout': 0.08387748568997636, 'lr': 0.00045949264757390654, 'batch_size': 8, 'epochs': 135}. Best is trial 3 with value: 8.874987602233887.
[I 2025-04-22 11:38:38,537] Trial 9 finished with value: 9.156498908996582 and parameters: {'n_layers': 1, 'n_units_l0': 476, 'dropout': 0.20931875917806864, 'lr': 0.0024146942715698315, 'batch_size': 8, 'epochs': 68}. Best is trial 3 with value: 8.874987602233887.
[I 2025-04-22 11:38:54,435] Trial 10 finished with value: 9.645099639892578 and parameters: {'n_layers': 2, 'n_units_l0': 164, 'n_units_l1': 67, 'dropout': 0.005579769761094679, 'lr': 0.00010909332006559373, 'batch_size': 8, 'epochs': 50}. Best is trial 3 with value: 8.874987602233887.
[I 2025-04-22 11:39:02,416] Trial 11 finished with value: 10.152426719665527 and parameters: {'n_layers': 1, 'n_units_l0': 315, 'dropout': 0.09263806731403111, 'lr': 0.00010120117043835367, 'batch_size': 8, 'epochs': 53}. Best is trial 3 with value: 8.874987602233887.
[I 2025-04-22 11:39:34,730] Trial 12 finished with value: 9.03930377960205 and parameters: {'n_layers': 2, 'n_units_l0': 403, 'n_units_l1': 176, 'dropout': 0.10340099203435313, 'lr': 0.0002720180626418762, 'batch_size': 8, 'epochs': 82}. Best is trial 3 with value: 8.874987602233887.
[I 2025-04-22 11:39:55,741] Trial 13 finished with value: 8.854167938232422 and parameters: {'n_layers': 1, 'n_units_l0': 500, 'dropout': 0.29557181759309886, 'lr': 0.001725680644271606, 'batch_size': 8, 'epochs': 85}. Best is trial 13 with value: 8.854167938232422.
[I 2025-04-22 11:40:17,117] Trial 14 finished with value: 9.994053840637207 and parameters: {'n_layers': 1, 'n_units_l0': 480, 'dropout': 0.2856591114581062, 'lr': 0.0032882117689412775, 'batch_size': 8, 'epochs': 86}. Best is trial 13 with value: 8.854167938232422.
[I 2025-04-22 11:41:10,888] Trial 15 finished with value: 8.847298622131348 and parameters: {'n_layers': 2, 'n_units_l0': 435, 'n_units_l1': 273, 'dropout': 0.33602141166386784, 'lr': 0.0001991418216435955, 'batch_size': 8, 'epochs': 116}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:42:05,127] Trial 16 finished with value: 9.26372241973877 and parameters: {'n_layers': 2, 'n_units_l0': 438, 'n_units_l1': 267, 'dropout': 0.3630897331020259, 'lr': 0.0007664172709439564, 'batch_size': 8, 'epochs': 118}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:42:23,508] Trial 17 finished with value: 9.607538223266602 and parameters: {'n_layers': 1, 'n_units_l0': 273, 'dropout': 0.3112459013840607, 'lr': 0.008860565391897085, 'batch_size': 8, 'epochs': 122}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:43:10,093] Trial 18 finished with value: 9.471973419189453 and parameters: {'n_layers': 2, 'n_units_l0': 411, 'n_units_l1': 243, 'dropout': 0.30844980601006894, 'lr': 0.001979003833582536, 'batch_size': 8, 'epochs': 110}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:43:33,445] Trial 19 finished with value: 9.37648868560791 and parameters: {'n_layers': 1, 'n_units_l0': 495, 'dropout': 0.39953026098609784, 'lr': 0.0049168259529650754, 'batch_size': 8, 'epochs': 92}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:43:49,917] Trial 20 finished with value: 9.286327362060547 and parameters: {'n_layers': 1, 'n_units_l0': 365, 'dropout': 0.2565621563546231, 'lr': 0.0001770237260847583, 'batch_size': 8, 'epochs': 107}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:44:56,794] Trial 21 finished with value: 10.89756965637207 and parameters: {'n_layers': 2, 'n_units_l0': 441, 'n_units_l1': 365, 'dropout': 0.33564138203499544, 'lr': 0.00018787456040935053, 'batch_size': 8, 'epochs': 132}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:45:29,659] Trial 22 finished with value: 10.114533424377441 and parameters: {'n_layers': 2, 'n_units_l0': 439, 'n_units_l1': 182, 'dropout': 0.270448745976519, 'lr': 0.00040527651660576927, 'batch_size': 8, 'epochs': 77}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:46:16,536] Trial 23 finished with value: 9.421072959899902 and parameters: {'n_layers': 2, 'n_units_l0': 500, 'n_units_l1': 325, 'dropout': 0.2298772276110469, 'lr': 0.0001952752713501051, 'batch_size': 8, 'epochs': 90}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:47:14,682] Trial 24 finished with value: 9.664874076843262 and parameters: {'n_layers': 2, 'n_units_l0': 450, 'n_units_l1': 192, 'dropout': 0.3449708664542614, 'lr': 0.0007745554390419221, 'batch_size': 8, 'epochs': 127}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:47:48,884] Trial 25 finished with value: 10.27015495300293 and parameters: {'n_layers': 2, 'n_units_l0': 425, 'n_units_l1': 446, 'dropout': 0.3941619047073881, 'lr': 0.0001482429027531193, 'batch_size': 8, 'epochs': 58}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:48:28,395] Trial 26 finished with value: 8.928629875183105 and parameters: {'n_layers': 2, 'n_units_l0': 278, 'n_units_l1': 91, 'dropout': 0.3070108756711473, 'lr': 0.00028226242180410854, 'batch_size': 8, 'epochs': 108}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:49:05,085] Trial 27 finished with value: 8.933368682861328 and parameters: {'n_layers': 2, 'n_units_l0': 461, 'n_units_l1': 309, 'dropout': 0.043556268815275606, 'lr': 0.0012493783030461875, 'batch_size': 8, 'epochs': 73}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:49:24,902] Trial 28 finished with value: 9.227032661437988 and parameters: {'n_layers': 1, 'n_units_l0': 50, 'dropout': 0.19055225575418727, 'lr': 0.0004391322346584766, 'batch_size': 8, 'epochs': 140}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:50:15,678] Trial 29 finished with value: 9.294020652770996 and parameters: {'n_layers': 2, 'n_units_l0': 378, 'n_units_l1': 427, 'dropout': 0.11814126956758803, 'lr': 0.004090878256026734, 'batch_size': 8, 'epochs': 100}. Best is trial 15 with value: 8.847298622131348.
[I 2025-04-22 11:50:15,679] A new study created in memory with name: no-name-9bf21293-139d-4368-aa88-5c9f0356fb28

Hyderabad Best MSE: 8.8473
Best Parameters: {'n_layers': 2, 'n_units_l0': 435, 'n_units_l1': 273, 'dropout': 0.33602141166386784, 'lr': 0.0001991418216435955, 'batch_size': 8, 'epochs': 116}

Running Optuna for Pune...

[I 2025-04-22 11:50:51,481] Trial 0 finished with value: 11.264348983764648 and parameters: {'n_layers': 1, 'n_units_l0': 447, 'dropout': 0.028526656876352696, 'lr': 0.00035871807879871387, 'batch_size': 8, 'epochs': 138}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:51:17,503] Trial 1 finished with value: 13.486594200134277 and parameters: {'n_layers': 2, 'n_units_l0': 278, 'n_units_l1': 300, 'dropout': 0.29439242134404414, 'lr': 0.0005062775696318495, 'batch_size': 8, 'epochs': 60}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:51:42,113] Trial 2 finished with value: 11.685722351074219 and parameters: {'n_layers': 1, 'n_units_l0': 421, 'dropout': 0.24806352831023717, 'lr': 0.0008581857555849387, 'batch_size': 8, 'epochs': 95}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:52:13,978] Trial 3 finished with value: 14.497031211853027 and parameters: {'n_layers': 2, 'n_units_l0': 422, 'n_units_l1': 252, 'dropout': 0.2776325277317989, 'lr': 0.009509848788269566, 'batch_size': 8, 'epochs': 71}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:52:31,050] Trial 4 finished with value: 13.28632640838623 and parameters: {'n_layers': 1, 'n_units_l0': 395, 'dropout': 0.005257207021292398, 'lr': 0.00047983896079480034, 'batch_size': 8, 'epochs': 107}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:52:39,506] Trial 5 finished with value: 13.962675094604492 and parameters: {'n_layers': 1, 'n_units_l0': 76, 'dropout': 0.21080988447156385, 'lr': 0.0014597251868340745, 'batch_size': 8, 'epochs': 58}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:52:50,724] Trial 6 finished with value: 12.527885437011719 and parameters: {'n_layers': 1, 'n_units_l0': 291, 'dropout': 0.38985465828448945, 'lr': 0.008745087601625151, 'batch_size': 8, 'epochs': 74}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:53:06,210] Trial 7 finished with value: 11.864706993103027 and parameters: {'n_layers': 1, 'n_units_l0': 180, 'dropout': 0.12767482024384189, 'lr': 0.00028755255000881903, 'batch_size': 8, 'epochs': 107}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:53:41,369] Trial 8 finished with value: 12.847480773925781 and parameters: {'n_layers': 2, 'n_units_l0': 241, 'n_units_l1': 438, 'dropout': 0.0034769883134630145, 'lr': 0.006394414658976818, 'batch_size': 8, 'epochs': 80}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:54:17,613] Trial 9 finished with value: 11.944609642028809 and parameters: {'n_layers': 2, 'n_units_l0': 364, 'n_units_l1': 351, 'dropout': 0.22664330257029242, 'lr': 0.0005436035385749401, 'batch_size': 8, 'epochs': 77}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:54:57,064] Trial 10 finished with value: 11.681415557861328 and parameters: {'n_layers': 1, 'n_units_l0': 495, 'dropout': 0.10715658606971089, 'lr': 0.00012232626752827394, 'batch_size': 8, 'epochs': 148}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:55:36,855] Trial 11 finished with value: 12.812359809875488 and parameters: {'n_layers': 1, 'n_units_l0': 493, 'dropout': 0.0930593968841951, 'lr': 0.00010443423901738577, 'batch_size': 8, 'epochs': 147}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:56:16,625] Trial 12 finished with value: 12.974784851074219 and parameters: {'n_layers': 1, 'n_units_l0': 482, 'dropout': 0.09892173138769336, 'lr': 0.00010698270706984889, 'batch_size': 8, 'epochs': 147}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:56:37,330] Trial 13 finished with value: 12.715720176696777 and parameters: {'n_layers': 1, 'n_units_l0': 347, 'dropout': 0.05841929949082703, 'lr': 0.00021089892537390784, 'batch_size': 8, 'epochs': 131}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:57:10,600] Trial 14 finished with value: 11.6333646774292 and parameters: {'n_layers': 1, 'n_units_l0': 486, 'dropout': 0.14418781118686685, 'lr': 0.00019939585114141204, 'batch_size': 8, 'epochs': 125}. Best is trial 0 with value: 11.264348983764648.
[I 2025-04-22 11:57:43,933] Trial 15 finished with value: 10.79545783996582 and parameters: {'n_layers': 1, 'n_units_l0': 451, 'dropout': 0.16218964509138323, 'lr': 0.001504634398533723, 'batch_size': 8, 'epochs': 125}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 11:58:04,241] Trial 16 finished with value: 11.784317016601562 and parameters: {'n_layers': 1, 'n_units_l0': 330, 'dropout': 0.17854895909717866, 'lr': 0.002212161226535575, 'batch_size': 8, 'epochs': 128}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 11:58:52,170] Trial 17 finished with value: 14.1708984375 and parameters: {'n_layers': 2, 'n_units_l0': 436, 'n_units_l1': 92, 'dropout': 0.04336331438094312, 'lr': 0.002912991128835582, 'batch_size': 8, 'epochs': 118}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 11:59:12,285] Trial 18 finished with value: 11.15942096710205 and parameters: {'n_layers': 1, 'n_units_l0': 181, 'dropout': 0.342999514308043, 'lr': 0.0010926911883806496, 'batch_size': 8, 'epochs': 135}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 11:59:29,127] Trial 19 finished with value: 11.1359281539917 and parameters: {'n_layers': 1, 'n_units_l0': 153, 'dropout': 0.3594403673032898, 'lr': 0.003876442702693283, 'batch_size': 8, 'epochs': 115}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 11:59:57,289] Trial 20 finished with value: 14.49821662902832 and parameters: {'n_layers': 2, 'n_units_l0': 62, 'n_units_l1': 58, 'dropout': 0.39527066425362706, 'lr': 0.004624480572050075, 'batch_size': 8, 'epochs': 94}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 12:00:14,019] Trial 21 finished with value: 11.88052749633789 and parameters: {'n_layers': 1, 'n_units_l0': 150, 'dropout': 0.34405087807181706, 'lr': 0.0012289839147317106, 'batch_size': 8, 'epochs': 116}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 12:00:30,820] Trial 22 finished with value: 11.304434776306152 and parameters: {'n_layers': 1, 'n_units_l0': 180, 'dropout': 0.3322280764396395, 'lr': 0.002616051757979518, 'batch_size': 8, 'epochs': 116}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 12:00:49,322] Trial 23 finished with value: 11.41236400604248 and parameters: {'n_layers': 1, 'n_units_l0': 118, 'dropout': 0.3451487118604001, 'lr': 0.000897063991068047, 'batch_size': 8, 'epochs': 135}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 12:01:04,035] Trial 24 finished with value: 11.880168914794922 and parameters: {'n_layers': 1, 'n_units_l0': 222, 'dropout': 0.17279472274380445, 'lr': 0.00398910186617357, 'batch_size': 8, 'epochs': 107}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 12:01:20,906] Trial 25 finished with value: 10.925800323486328 and parameters: {'n_layers': 1, 'n_units_l0': 223, 'dropout': 0.3036602234460372, 'lr': 0.0017175231251882446, 'batch_size': 8, 'epochs': 122}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 12:01:34,681] Trial 26 finished with value: 13.5670166015625 and parameters: {'n_layers': 1, 'n_units_l0': 247, 'dropout': 0.30032597993505383, 'lr': 0.002066427222338509, 'batch_size': 8, 'epochs': 100}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 12:01:51,195] Trial 27 finished with value: 11.668817520141602 and parameters: {'n_layers': 1, 'n_units_l0': 124, 'dropout': 0.258934952910061, 'lr': 0.0017440633701257034, 'batch_size': 8, 'epochs': 124}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 12:02:03,287] Trial 28 finished with value: 11.27370834350586 and parameters: {'n_layers': 1, 'n_units_l0': 305, 'dropout': 0.3058049733313427, 'lr': 0.0032523831580735622, 'batch_size': 8, 'epochs': 86}. Best is trial 15 with value: 10.79545783996582.
[I 2025-04-22 12:02:19,957] Trial 29 finished with value: 11.772980690002441 and parameters: {'n_layers': 1, 'n_units_l0': 239, 'dropout': 0.3669569874965012, 'lr': 0.004596524383154153, 'batch_size': 8, 'epochs': 121}. Best is trial 15 with value: 10.79545783996582.

Pune Best MSE: 10.7955
Best Parameters: {'n_layers': 1, 'n_units_l0': 451, 'dropout': 0.16218964509138323, 'lr': 0.001504634398533723, 'batch_size': 8, 'epochs': 125}

In [41]:
results

{'Bangalore': FrozenTrial(number=5, state=TrialState.COMPLETE, values=[7.139224052429199], datetime_start=datetime.datetime(2025, 4, 22, 11, 23, 9, 534554), datetime_complete=datetime.datetime(2025, 4, 22, 11, 23, 34, 413962), params={'n_layers': 2, 'n_units_l0': 400, 'n_units_l1': 175, 'dropout': 0.17405013132252034, 'lr': 0.0011864757981162946, 'batch_size': 8, 'epochs': 88}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_layers': IntDistribution(high=2, log=False, low=1, step=1), 'n_units_l0': IntDistribution(high=500, log=False, low=50, step=1), 'n_units_l1': IntDistribution(high=500, log=False, low=50, step=1), 'dropout': FloatDistribution(high=0.4, log=False, low=0.0, step=None), 'lr': FloatDistribution(high=0.01, log=True, low=0.0001, step=None), 'batch_size': CategoricalDistribution(choices=(8,)), 'epochs': IntDistribution(high=150, log=False, low=50, step=1)}, trial_id=5, value=None),
 'Hyderabad': FrozenTrial(number=15, state=TrialState.COMPLETE, values=[8.847298622131348], datetime_start=datetime.datetime(2025, 4, 22, 11, 40, 17, 118526), datetime_complete=datetime.datetime(2025, 4, 22, 11, 41, 10, 888000), params={'n_layers': 2, 'n_units_l0': 435, 'n_units_l1': 273, 'dropout': 0.33602141166386784, 'lr': 0.0001991418216435955, 'batch_size': 8, 'epochs': 116}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_layers': IntDistribution(high=2, log=False, low=1, step=1), 'n_units_l0': IntDistribution(high=500, log=False, low=50, step=1), 'n_units_l1': IntDistribution(high=500, log=False, low=50, step=1), 'dropout': FloatDistribution(high=0.4, log=False, low=0.0, step=None), 'lr': FloatDistribution(high=0.01, log=True, low=0.0001, step=None), 'batch_size': CategoricalDistribution(choices=(8,)), 'epochs': IntDistribution(high=150, log=False, low=50, step=1)}, trial_id=15, value=None),
 'Pune': FrozenTrial(number=15, state=TrialState.COMPLETE, values=[10.79545783996582], datetime_start=datetime.datetime(2025, 4, 22, 11, 57, 10, 601178), datetime_complete=datetime.datetime(2025, 4, 22, 11, 57, 43, 932876), params={'n_layers': 1, 'n_units_l0': 451, 'dropout': 0.16218964509138323, 'lr': 0.001504634398533723, 'batch_size': 8, 'epochs': 125}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_layers': IntDistribution(high=2, log=False, low=1, step=1), 'n_units_l0': IntDistribution(high=500, log=False, low=50, step=1), 'dropout': FloatDistribution(high=0.4, log=False, low=0.0, step=None), 'lr': FloatDistribution(high=0.01, log=True, low=0.0001, step=None), 'batch_size': CategoricalDistribution(choices=(8,)), 'epochs': IntDistribution(high=150, log=False, low=50, step=1)}, trial_id=15, value=None)}

# Evaluating the Model and Visualizing the Results

In [42]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [43]:
def evaluate_predictions(y_true, y_pred):
    y_true = y_true.squeeze()
    y_pred = y_pred.squeeze()
    
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    
    # NSE
    nse = 1 - np.sum((y_true - y_pred)**2) / np.sum((y_true - np.mean(y_true))**2)
    
    # RSR = RMSE / STDEV of observed
    rsr = rmse / np.std(y_true)
    
    # PBIAS
    pbias = 100 * np.sum(y_true - y_pred) / np.sum(y_true)

    return {
        "MSE": mse,
        "MAE": mae,
        "R²": r2,
        "NSE": nse,
        "RSR": rsr,
        "PBIAS": pbias
    }

In [44]:
def plot_predictions(y_true, y_pred, title="Prediction vs Ground Truth"):
    plt.figure(figsize=(10, 5))
    plt.plot(y_true.squeeze(), label="True", alpha=0.7)
    plt.plot(y_pred.squeeze(), label="Predicted", alpha=0.7)
    plt.title(title)
    plt.xlabel("Time Step")
    plt.ylabel("LST")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

In [45]:
from optuna.visualization.matplotlib import plot_optimization_history

def plot_optuna_loss(study, title="Optuna Loss Over Trials"):
    fig = plot_optimization_history(study)
    fig.gca().set_title(title)
    plt.tight_layout()
    plt.show()

In [46]:
def train_final_model(X_train, y_train, X_test, y_test, best_params):
    hidden_sizes = [best_params[f"n_units_l{i}"] for i in range(best_params["n_layers"])]
    model = ANN(X_train.shape[1], hidden_sizes, best_params["dropout"])
    optimizer = torch.optim.Adam(model.parameters(), lr=best_params["lr"])
    criterion = nn.MSELoss()

    dataset = torch.utils.data.TensorDataset(X_train, y_train)
    loader = torch.utils.data.DataLoader(dataset, batch_size=best_params["batch_size"], shuffle=True)

    model.train()
    for epoch in range(best_params["epochs"]):
        for X_batch, y_batch in loader:
            optimizer.zero_grad()
            loss = criterion(model(X_batch), y_batch)
            loss.backward()
            optimizer.step()

    return model

In [47]:
import plotly.graph_objects as go
def plot_predictions_plotly(y_true, y_pred, title="Prediction vs Ground Truth (Test Data)"):
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        y=y_true.squeeze(),
        mode='lines',
        name='True',
        line=dict(color='blue')
    ))

    fig.add_trace(go.Scatter(
        y=y_pred.squeeze(),
        mode='lines',
        name='Predicted',
        line=dict(color='orange')
    ))

    fig.update_layout(
        title=title,
        xaxis_title="Time Step (Test Set)",
        yaxis_title="LST",
        legend=dict(x=0.01, y=0.99),
        template='plotly_white',
        height=500,
        width=1000
    )

    fig.show()

In [48]:
blr_best_params = results["Bangalore"].params
pune_best_params = results["Pune"].params
hyd_best_params = results["Hyderabad"].params

In [49]:
blr_model = train_final_model(
    blr_X_train_tensor, blr_y_train_tensor,
    blr_X_test_tensor, blr_y_test_tensor,
    blr_best_params
)

In [50]:
blr_model.eval()

ANN(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=400, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.17405013132252034, inplace=False)
    (3): Linear(in_features=400, out_features=175, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.17405013132252034, inplace=False)
    (6): Linear(in_features=175, out_features=1, bias=True)
  )
)

In [51]:
with torch.no_grad():
    y_pred_blr = blr_model(blr_X_test_tensor).numpy()
    y_true_blr = blr_y_test_tensor.numpy()

In [52]:
metrics_blr = evaluate_predictions(y_true_blr, y_pred_blr)
print("Bangalore Metrics:")
for k, v in metrics_blr.items():
    print(f"{k}: {v:.4f}")

Bangalore Metrics:
MSE: 7.9490
MAE: 2.1733
R²: 0.6562
NSE: 0.6562
RSR: 0.5864
PBIAS: -1.7650

In [53]:
plot_predictions_plotly(y_true_blr, y_pred_blr, title="Bangalore's Prediction vs Ground Truth (Test)")

In [54]:
hyd_model = train_final_model(
    hyd_X_train_tensor, hyd_y_train_tensor,
    hyd_X_test_tensor, hyd_y_test_tensor,
    hyd_best_params
)

In [55]:
hyd_model.eval()

ANN(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=435, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.33602141166386784, inplace=False)
    (3): Linear(in_features=435, out_features=273, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.33602141166386784, inplace=False)
    (6): Linear(in_features=273, out_features=1, bias=True)
  )
)

In [56]:
with torch.no_grad():
    y_pred_hyd = hyd_model(hyd_X_test_tensor).numpy()
    y_true_hyd = hyd_y_test_tensor.numpy()

In [57]:
metrics_hyd = evaluate_predictions(y_true_hyd, y_pred_hyd)
print("Hyderabad Metrics:")
for k, v in metrics_hyd.items():
    print(f"{k}: {v:.4f}")

Hyderabad Metrics:
MSE: 9.0665
MAE: 2.2921
R²: 0.6035
NSE: 0.6035
RSR: 0.6297
PBIAS: -1.2928

In [58]:
plot_predictions_plotly(y_true_hyd, y_pred_hyd, title="Hyderabad's Prediction vs Ground Truth (Test)")

In [59]:
pune_model = train_final_model(
    pune_X_train_tensor, pune_y_train_tensor,
    pune_X_test_tensor, pune_y_test_tensor,
    pune_best_params
)

In [60]:
pune_model.eval()

ANN(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=451, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.16218964509138323, inplace=False)
    (3): Linear(in_features=451, out_features=1, bias=True)
  )
)

In [61]:
with torch.no_grad():
    y_pred_pune = pune_model(pune_X_test_tensor).numpy()
    y_true_pune = pune_y_test_tensor.numpy()

In [62]:
metrics_pune = evaluate_predictions(y_true_pune, y_pred_pune)
print("Pune's Metrics:")
for k, v in metrics_pune.items():
    print(f"{k}: {v:.4f}")

Pune's Metrics:
MSE: 14.4300
MAE: 2.8466
R²: 0.6809
NSE: 0.6809
RSR: 0.5649
PBIAS: -5.3593

In [63]:
plot_predictions_plotly(y_true_pune, y_pred_pune, title="Pune's Prediction vs Ground Truth (Test)")

# Storing the model for future use

In [64]:
os.makedirs('../Models/ANN', exist_ok=True)

In [65]:
torch.save(blr_model.state_dict(), "../Models/ANN/blr_ann_model.pth")

In [66]:
torch.save(hyd_model.state_dict(), "../Models/ANN/hyd_ann_model.pth")

In [67]:
torch.save(pune_model.state_dict(), "../Models/ANN/pune_ann_model.pth")