# Importing the Necessary Libraries

In [680]:
import pandas as pd
import numpy as np
import os

# Reading the Datasets

In [681]:
blr_lst = pd.read_csv("../Data/LST_Daily_BLR_GF.csv")
hyd_lst = pd.read_csv("../Data/LST_Daily_HYD_GF.csv")  
pune_lst = pd.read_csv("../Data/LST_Daily_PUNE_GF.csv")

In [682]:
# Daily Dew Point Temperatures
blr_dpt = pd.read_csv("../Data/DPT_BLR.csv")
hyd_dpt = pd.read_csv("../Data/DPT_HYD.csv")
pune_dpt = pd.read_csv("../Data/DPT_PUNE.csv")

In [683]:
# Daily Atomospheric Pressure
blr_ap = pd.read_csv("../Data/AP_BLR.csv")
hyd_ap = pd.read_csv("../Data/AP_HYD.csv")
pune_ap = pd.read_csv("../Data/AP_PUNE.csv")

In [684]:
# Wind Components
blr_wind = pd.read_csv("../Data/WindComponents_BLR.csv")
hyd_wind = pd.read_csv("../Data/WindComponents_HYD.csv")
pune_wind = pd.read_csv("../Data/WindComponents_BLR.csv")

In [685]:
blr_at = pd.read_csv("../Data/AT_BLR.csv")
hyd_at = pd.read_csv("../Data/AT_HYD.csv")
pune_at = pd.read_csv("../Data/AT_PUNE.csv")

# Creating the master dataframes

In [686]:
blr_df = pd.DataFrame(columns=['Date', 'DPT', 'AP', 'WS', 'WSD', 'RH', 'LST'])
hyd_df = pd.DataFrame(columns=['Date', 'DPT', 'AP', 'WS', 'WSD', 'RH', 'LST'])
pune_df = pd.DataFrame(columns=['Date', 'DPT', 'AP', 'WS', 'WSD', 'RH', 'LST'])

# Removing necessary columns

In [687]:
hyd_lst

,system:index,LST_Celsius,date,.geo
0,gf_Day2003_001,352.530271,2003-01-01,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,gf_Day2003_002,316.605346,2003-01-02,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,gf_Day2003_003,300.858490,2003-01-03,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,gf_Day2003_004,305.698638,2003-01-04,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,gf_Day2003_005,318.788953,2003-01-05,"{""type"":""MultiPoint"",""coordinates"":[]}"
...,...,...,...,...
6565,gf_Day2020_361,322.623439,2020-12-26,"{""type"":""MultiPoint"",""coordinates"":[]}"
6566,gf_Day2020_362,337.966272,2020-12-27,"{""type"":""MultiPoint"",""coordinates"":[]}"
6567,gf_Day2020_363,317.480700,2020-12-28,"{""type"":""MultiPoint"",""coordinates"":[]}"
6568,gf_Day2020_364,330.915973,2020-12-29,"{""type"":""MultiPoint"",""coordinates"":[]}"
6569,gf_Day2020_365,303.463004,2020-12-30,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [688]:
pune_dpt

,system:index,date,dewPointTemp,.geo
0,20030101,2003-01-01,280.250958,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,20030102,2003-01-02,283.634796,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,20030103,2003-01-03,285.756104,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,20030104,2003-01-04,285.796417,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,20030105,2003-01-05,286.216706,"{""type"":""MultiPoint"",""coordinates"":[]}"
...,...,...,...,...
6568,20201225,2020-12-25,285.246190,"{""type"":""MultiPoint"",""coordinates"":[]}"
6569,20201226,2020-12-26,286.531471,"{""type"":""MultiPoint"",""coordinates"":[]}"
6570,20201227,2020-12-27,286.969016,"{""type"":""MultiPoint"",""coordinates"":[]}"
6571,20201228,2020-12-28,286.981078,"{""type"":""MultiPoint"",""coordinates"":[]}"
6572,20201229,2020-12-29,286.665426,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [689]:
pune_ap

,system:index,date,surfacePressure,.geo
0,20030101,2003-01-01,94196.132322,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,20030102,2003-01-02,94267.543314,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,20030103,2003-01-03,94288.145684,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,20030104,2003-01-04,94300.922674,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,20030105,2003-01-05,94376.252726,"{""type"":""MultiPoint"",""coordinates"":[]}"
...,...,...,...,...
6568,20201225,2020-12-25,94105.388525,"{""type"":""MultiPoint"",""coordinates"":[]}"
6569,20201226,2020-12-26,94226.309255,"{""type"":""MultiPoint"",""coordinates"":[]}"
6570,20201227,2020-12-27,94128.769184,"{""type"":""MultiPoint"",""coordinates"":[]}"
6571,20201228,2020-12-28,94063.093892,"{""type"":""MultiPoint"",""coordinates"":[]}"
6572,20201229,2020-12-29,94027.122821,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [690]:
blr_wind

,system:index,date,u_component_of_wind_10m,v_component_of_wind_10m,.geo
0,20030101,2003-01-01,-0.327114,0.513567,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,20030102,2003-01-02,-2.819963,1.043748,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,20030103,2003-01-03,-2.829072,0.494821,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,20030104,2003-01-04,-2.668422,0.231232,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,20030105,2003-01-05,-3.091901,0.284496,"{""type"":""MultiPoint"",""coordinates"":[]}"
...,...,...,...,...,...
6569,20201226,2020-12-26,-2.219871,-0.649711,"{""type"":""MultiPoint"",""coordinates"":[]}"
6570,20201227,2020-12-27,-2.150850,-0.694880,"{""type"":""MultiPoint"",""coordinates"":[]}"
6571,20201228,2020-12-28,-1.928350,-0.544585,"{""type"":""MultiPoint"",""coordinates"":[]}"
6572,20201229,2020-12-29,-2.369977,0.113602,"{""type"":""MultiPoint"",""coordinates"":[]}"
6573,20201230,2020-12-30,-3.265377,-0.210665,"{""type"":""MultiPoint"",""coordinates"":[]}"

### Looking at the data, we see that that system:index, .geo are unnecessary for our analysis, hence we shall drop them.

In [691]:
def dropColumns(df):
    return df.drop(columns=['system:index', '.geo'], errors='ignore')

In [692]:
datasets = [blr_lst, hyd_lst, pune_lst,
            blr_dpt, hyd_dpt, pune_dpt,
            blr_ap, hyd_ap, pune_ap,
            blr_wind, hyd_wind, pune_wind, blr_at, hyd_at, pune_at]

In [693]:
datasets = [dropColumns(df) for df in datasets]

In [694]:
(blr_lst, hyd_lst, pune_lst,
 blr_dpt, hyd_dpt, pune_dpt,
 blr_ap, hyd_ap, pune_ap,
 blr_wind, hyd_wind, pune_wind, blr_at, hyd_at, pune_at) = datasets

### Dropping Duplicates

In [695]:
def clean_dates(df):
    df['date'] = pd.to_datetime(df['date'], errors='coerce').dt.date
    df = df.dropna(subset=['date'])
    df = df.drop_duplicates(subset='date')
    return df

In [696]:
datasets = [blr_lst, hyd_lst, pune_lst,
            blr_dpt, hyd_dpt, pune_dpt,
            blr_ap, hyd_ap, pune_ap,
            blr_wind, hyd_wind, pune_wind, blr_at, hyd_at, pune_at]

In [697]:
datasets = [clean_dates(df) for df in datasets]

In [698]:
(blr_lst, hyd_lst, pune_lst,
 blr_dpt, hyd_dpt, pune_dpt,
 blr_ap, hyd_ap, pune_ap,
 blr_wind, hyd_wind, pune_wind, blr_at, hyd_at, pune_at) = datasets

### We can see that there is a mismatch between the number of entries across different datasets. For that I shall take all the common entries based on date in the tables

In [699]:
# Extract date sets
lst_dates = set(blr_lst['date']) & set(hyd_lst['date']) & set(pune_lst['date'])
dpt_dates = set(blr_dpt['date']) & set(hyd_dpt['date']) & set(pune_dpt['date'])
ap_dates = set(blr_ap['date']) & set(hyd_ap['date']) & set(pune_ap['date'])
wind_dates = set(blr_wind['date']) & set(hyd_wind['date']) & set(pune_wind['date'])
at_dates = set(blr_at['date']) & set(hyd_at['date']) & set(pune_at['date'])

In [700]:
# Final common dates
common_dates = lst_dates & dpt_dates & ap_dates & wind_dates & at_dates
common_dates = sorted(list(common_dates))  # Ensure chronological order

In [701]:
def filter_dates(df, common_dates):
    return df[df['date'].isin(common_dates)].sort_values('date').reset_index(drop=True)

In [702]:
blr_lst_daily = filter_dates(blr_lst, common_dates)
hyd_lst_daily = filter_dates(hyd_lst, common_dates)
pune_lst_daily = filter_dates(pune_lst, common_dates)

In [703]:
blr_dpt_daily = filter_dates(blr_dpt, common_dates)
hyd_dpt_daily = filter_dates(hyd_dpt, common_dates)
pune_dpt_daily = filter_dates(pune_dpt, common_dates)

In [704]:
blr_ap_daily = filter_dates(blr_ap, common_dates)
hyd_ap_daily = filter_dates(hyd_ap, common_dates)
pune_ap_daily = filter_dates(pune_ap, common_dates)

In [705]:

blr_wind_daily = filter_dates(blr_wind, common_dates)
hyd_wind_daily = filter_dates(hyd_wind, common_dates)
pune_wind_daily = filter_dates(pune_wind, common_dates)

In [706]:
blr_at_daily = filter_dates(blr_at, common_dates)
hyd_at_daily = filter_dates(hyd_at, common_dates)
pune_at_daily = filter_dates(pune_at, common_dates)

In [707]:
lst_tables = [blr_lst_daily, hyd_lst_daily, pune_lst_daily]
dpt_tables = [blr_dpt_daily, hyd_dpt_daily, pune_dpt_daily]
ap_tables = [blr_ap_daily, hyd_ap_daily, pune_ap_daily]
wind_tables = [blr_wind_daily, hyd_wind_daily, pune_wind_daily]
at_tables = [blr_at_daily, hyd_at_daily, pune_at_daily]

In [708]:
for table in lst_tables:
    print(table.shape)

(6558, 2)
(6558, 2)
(6558, 2)

In [709]:
for table in dpt_tables:
    print(table.shape)

(6558, 2)
(6558, 2)
(6558, 2)

In [710]:
for table in ap_tables:
    print(table.shape)

(6558, 2)
(6558, 2)
(6558, 2)

In [711]:
for table in wind_tables:
    print(table.shape)

(6558, 3)
(6558, 3)
(6558, 3)

In [712]:
for table in at_tables:
    print(table.shape)

(6558, 2)
(6558, 2)
(6558, 2)

### Calculating the magnitude of wind speed and direction

In [713]:
def calculateWindSpeed(df : pd.DataFrame) -> pd.DataFrame:
    """
    Calculate wind speed from u and v components.
    """
    df['WS'] = np.sqrt(df['u_component_of_wind_10m']**2 + df['v_component_of_wind_10m']**2)
    return df

In [714]:
def calculateWindDirection(df : pd.DataFrame) -> pd.DataFrame:
    """
    Calculate wind direction from u and v components.
    """
    df['WSD'] = np.arctan2(df['u_component_of_wind_10m'], df['v_component_of_wind_10m']) * 180 / np.pi
    df['WSD'] = (df['WSD'] + 360) % 360  # Normalize to [0, 360)
    return df

In [715]:
blr_wind_daily = calculateWindSpeed(blr_wind_daily)
pune_wind_daily = calculateWindSpeed(pune_wind_daily)
hyd_wind_daily = calculateWindSpeed(hyd_wind_daily)

In [716]:
blr_wind_daily = calculateWindDirection(blr_wind_daily)
pune_wind_daily = calculateWindDirection(pune_wind_daily)
hyd_wind_daily = calculateWindDirection(hyd_wind_daily)

In [717]:
blr_wind_daily

,date,u_component_of_wind_10m,v_component_of_wind_10m,WS,WSD
0,2003-01-01,-0.327114,0.513567,0.608896,327.505071
1,2003-01-02,-2.819963,1.043748,3.006925,290.310937
2,2003-01-03,-2.829072,0.494821,2.872020,279.921010
3,2003-01-04,-2.668422,0.231232,2.678422,274.952584
4,2003-01-05,-3.091901,0.284496,3.104962,275.257170
...,...,...,...,...,...
6553,2020-12-25,-2.128752,-0.319760,2.152634,261.457477
6554,2020-12-26,-2.219871,-0.649711,2.312996,253.686322
6555,2020-12-27,-2.150850,-0.694880,2.260313,252.095788
6556,2020-12-28,-1.928350,-0.544585,2.003774,254.229795
6557,2020-12-29,-2.369977,0.113602,2.372698,272.744304

In [718]:
hyd_wind_daily

,date,u_component_of_wind_10m,v_component_of_wind_10m,WS,WSD
0,2003-01-01,-2.039009,-1.773130,2.702138,228.989644
1,2003-01-02,-2.833919,0.902780,2.974241,287.669929
2,2003-01-03,-2.358774,1.878723,3.015529,308.536731
3,2003-01-04,-1.624962,0.915442,1.865083,299.395258
4,2003-01-05,-2.278999,-0.198965,2.287668,265.010524
...,...,...,...,...,...
6553,2020-12-25,-1.866285,0.760561,2.015309,292.172202
6554,2020-12-26,-1.682583,0.428816,1.736367,284.297801
6555,2020-12-27,-1.665262,0.550966,1.754041,288.307250
6556,2020-12-28,-1.744834,1.003069,2.012608,299.893708
6557,2020-12-29,-2.307411,1.075839,2.545894,294.997468

In [719]:
pune_wind_daily

,date,u_component_of_wind_10m,v_component_of_wind_10m,WS,WSD
0,2003-01-01,-0.327114,0.513567,0.608896,327.505071
1,2003-01-02,-2.819963,1.043748,3.006925,290.310937
2,2003-01-03,-2.829072,0.494821,2.872020,279.921010
3,2003-01-04,-2.668422,0.231232,2.678422,274.952584
4,2003-01-05,-3.091901,0.284496,3.104962,275.257170
...,...,...,...,...,...
6553,2020-12-25,-2.128752,-0.319760,2.152634,261.457477
6554,2020-12-26,-2.219871,-0.649711,2.312996,253.686322
6555,2020-12-27,-2.150850,-0.694880,2.260313,252.095788
6556,2020-12-28,-1.928350,-0.544585,2.003774,254.229795
6557,2020-12-29,-2.369977,0.113602,2.372698,272.744304

In [720]:
blr_lst_daily

      LST_Celsius        date
0      309.395285  2003-01-01
1      311.791133  2003-01-02
2      330.457050  2003-01-03
3      382.669334  2003-01-04
4      331.853939  2003-01-05
...           ...         ...
6553   321.187581  2020-12-25
6554   320.680087  2020-12-26
6555   345.393270  2020-12-27
6556   313.103988  2020-12-28
6557   329.456816  2020-12-29

[6558 rows x 2 columns]

### Combining all the information to a single dataframe

In [721]:
blr_df['Date'] = blr_lst_daily['date']
blr_df['LST'] = blr_lst_daily['LST_Celsius']
blr_df['DPT'] = blr_dpt_daily['dewPointTemp']
blr_df['AP'] = blr_ap_daily['surfacePressure']
blr_df['WS'] = blr_wind_daily['WS']
blr_df['WSD'] = blr_wind_daily['WSD']

In [722]:
hyd_df['Date'] = hyd_lst_daily['date']
hyd_df['LST'] = hyd_lst_daily['LST_Celsius']
hyd_df['DPT'] = hyd_dpt_daily['dewPointTemp']
hyd_df['AP'] = hyd_ap_daily['surfacePressure']
hyd_df['WS'] = hyd_wind_daily['WS']
hyd_df['WSD'] = hyd_wind_daily['WSD']

In [723]:
pune_df['Date'] = pune_lst_daily['date']
pune_df['LST'] = pune_lst_daily['LST_Celsius']
pune_df['DPT'] = pune_dpt_daily['dewPointTemp']
pune_df['AP'] = pune_ap_daily['surfacePressure']
pune_df['WS'] = pune_wind_daily['WS']
pune_df['WSD'] = pune_wind_daily['WSD']

In [724]:
blr_df.isna().sum()

Date       0
DPT        0
AP         0
WS         0
WSD        0
RH      6558
LST        0
dtype: int64

In [725]:
hyd_df.isna().sum()

Date       0
DPT        0
AP         0
WS         0
WSD        0
RH      6558
LST        0
dtype: int64

In [726]:
pune_df.isna().sum()

Date       0
DPT        0
AP         0
WS         0
WSD        0
RH      6558
LST        0
dtype: int64

## Converting the units to Celsisus, metres/second, pascal to hPa

In [727]:
def lstCorrect(df : pd.DataFrame) -> pd.DataFrame:
    """
    Corrects the LST values based on the RH values.
    """
    df['LST'] = df['LST'] * 0.1
    return df

In [728]:
def toCelsius(df : pd.DataFrame, col: str) -> pd.DataFrame:
    """
    Converts Kelvin to Celsius.
    """
    df[col] = df[col] - 273.15
    return df

In [729]:
def paTohPa(df : pd.DataFrame, col: str) -> pd.DataFrame:
    """
    Converts Pa to hPa.
    """
    df[col] = df[col] / 100
    return df

In [730]:
blr_df = lstCorrect(blr_df)
hyd_df = lstCorrect(hyd_df)
pune_df = lstCorrect(pune_df)

In [731]:
blr_df = toCelsius(blr_df, 'DPT')
hyd_df = toCelsius(hyd_df, 'DPT')
pune_df = toCelsius(pune_df, 'DPT')

In [732]:
blr_df = paTohPa(blr_df, 'AP')
pune_df = paTohPa(pune_df, 'AP')
hyd_df = paTohPa(hyd_df, 'AP')

In [733]:
blr_df

            Date        DPT          AP        WS         WSD   RH        LST
0     2003-01-01  12.498648  916.589625  0.608896  327.505071  NaN  30.939528
1     2003-01-02  12.825784  918.004624  3.006925  290.310937  NaN  31.179113
2     2003-01-03  12.970981  918.453619  2.872020  279.921010  NaN  33.045705
3     2003-01-04  12.445614  917.966755  2.678422  274.952584  NaN  38.266933
4     2003-01-05  14.071074  918.579933  3.104962  275.257170  NaN  33.185394
...          ...        ...         ...       ...         ...  ...        ...
6553  2020-12-25  13.500707  916.151180  2.152634  261.457477  NaN  32.118758
6554  2020-12-26  12.901577  917.194971  2.312996  253.686322  NaN  32.068009
6555  2020-12-27  12.950693  916.302854  2.260313  252.095788  NaN  34.539327
6556  2020-12-28  10.830827  916.237697  2.003774  254.229795  NaN  31.310399
6557  2020-12-29  16.207934  915.751192  2.372698  272.744304  NaN  32.945682

[6558 rows x 7 columns]

In [734]:
hyd_df

            Date        DPT          AP        WS         WSD   RH        LST
0     2003-01-01   9.801921  952.321702  2.702138  228.989644  NaN  35.253027
1     2003-01-02  12.894156  953.896739  2.974241  287.669929  NaN  31.660535
2     2003-01-03  16.945643  954.471306  3.015529  308.536731  NaN  30.085849
3     2003-01-04  17.761199  954.172469  1.865083  299.395258  NaN  30.569864
4     2003-01-05  14.281283  954.395644  2.287668  265.010524  NaN  31.878895
...          ...        ...         ...       ...         ...  ...        ...
6553  2020-12-25  13.330685  951.670802  2.015309  292.172202  NaN  30.396700
6554  2020-12-26  14.027632  952.521458  1.736367  284.297801  NaN  32.262344
6555  2020-12-27  13.223768  951.342613  1.754041  288.307250  NaN  33.796627
6556  2020-12-28  12.504071  951.101661  2.012608  299.893708  NaN  31.748070
6557  2020-12-29  12.890767  951.123203  2.545894  294.997468  NaN  33.091597

[6558 rows x 7 columns]

In [735]:
pune_df

            Date        DPT          AP        WS         WSD   RH        LST
0     2003-01-01   7.100958  941.961323  0.608896  327.505071  NaN  34.246204
1     2003-01-02  10.484796  942.675433  3.006925  290.310937  NaN  35.734294
2     2003-01-03  12.606104  942.881457  2.872020  279.921010  NaN  32.590960
3     2003-01-04  12.646417  943.009227  2.678422  274.952584  NaN  35.435619
4     2003-01-05  13.066706  943.762527  3.104962  275.257170  NaN  34.235347
...          ...        ...         ...       ...         ...  ...        ...
6553  2020-12-25  12.096190  941.053885  2.152634  261.457477  NaN  33.209944
6554  2020-12-26  13.381471  942.263093  2.312996  253.686322  NaN  31.352555
6555  2020-12-27  13.819016  941.287692  2.260313  252.095788  NaN  33.862652
6556  2020-12-28  13.831078  940.630939  2.003774  254.229795  NaN  32.318171
6557  2020-12-29  13.515426  940.271228  2.372698  272.744304  NaN  34.509701

[6558 rows x 7 columns]

# Calculating RH

In [736]:
blr_at_daily = toCelsius(blr_at_daily, 'airTemp')
hyd_at_daily = toCelsius(hyd_at_daily, 'airTemp')
pune_at_daily = toCelsius(pune_at_daily, 'airTemp')

In [737]:
blr_df['AT'] = blr_at_daily['airTemp']
hyd_df['AT'] = hyd_at_daily['airTemp']
pune_df['AT'] = pune_at_daily['airTemp']

In [738]:
def compute_rh_from_air_temp(df, temp_col='T', dew_point_col='DP', rh_col='RH'):
    """
    Compute Relative Humidity and return the full DataFrame with a new RH column.

    Parameters:
    - df: pandas DataFrame
    - temp_col: temperature column name in °C
    - dew_point_col: dew point temperature column name in °C
    - rh_col: name for the RH column to be added

    Returns:
    - Modified DataFrame with an added RH column
    """
    T = df[temp_col]
    DP = df[dew_point_col]

    rh = ((112 - 0.1 * T + DP) / (112 + 0.9 * T)) * 100
    df[rh_col] = rh.clip(lower=0, upper=100)
    df.drop(columns = [temp_col], inplace=True)
    return df

In [739]:
blr_df = compute_rh_from_air_temp(blr_df, temp_col='AT', dew_point_col='DPT')
hyd_df = compute_rh_from_air_temp(hyd_df, temp_col='AT', dew_point_col='DPT')
pune_df = compute_rh_from_air_temp(pune_df, temp_col='AT', dew_point_col='DPT')

In [740]:
blr_df

,Date,DPT,AP,WS,WSD,RH,LST
0,2003-01-01,12.498648,916.589625,0.608896,327.505071,93.194473,30.939528
1,2003-01-02,12.825784,918.004624,3.006925,290.310937,93.578218,31.179113
2,2003-01-03,12.970981,918.453619,2.872020,279.921010,94.227231,33.045705
3,2003-01-04,12.445614,917.966755,2.678422,274.952584,93.297114,38.266933
4,2003-01-05,14.071074,918.579933,3.104962,275.257170,94.353249,33.185394
...,...,...,...,...,...,...,...
6553,2020-12-25,13.500707,916.151180,2.152634,261.457477,95.470006,32.118758
6554,2020-12-26,12.901577,917.194971,2.312996,253.686322,95.361429,32.068009
6555,2020-12-27,12.950693,916.302854,2.260313,252.095788,94.854902,34.539327
6556,2020-12-28,10.830827,916.237697,2.003774,254.229795,93.468912,31.310399
6557,2020-12-29,16.207934,915.751192,2.372698,272.744304,96.359538,32.945682

In [741]:
hyd_df

,Date,DPT,AP,WS,WSD,RH,LST
0,2003-01-01,9.801921,952.321702,2.702138,228.989644,91.137446,35.253027
1,2003-01-02,12.894156,953.896739,2.974241,287.669929,92.938629,31.660535
2,2003-01-03,16.945643,954.471306,3.015529,308.536731,96.690377,30.085849
3,2003-01-04,17.761199,954.172469,1.865083,299.395258,98.016959,30.569864
4,2003-01-05,14.281283,954.395644,2.287668,265.010524,93.245268,31.878895
...,...,...,...,...,...,...,...
6553,2020-12-25,13.330685,951.670802,2.015309,292.172202,94.673562,30.396700
6554,2020-12-26,14.027632,952.521458,1.736367,284.297801,94.788311,32.262344
6555,2020-12-27,13.223768,951.342613,1.754041,288.307250,94.039085,33.796627
6556,2020-12-28,12.504071,951.101661,2.012608,299.893708,93.248170,31.748070
6557,2020-12-29,12.890767,951.123203,2.545894,294.997468,93.764521,33.091597

In [742]:
pune_df

,Date,DPT,AP,WS,WSD,RH,LST
0,2003-01-01,7.100958,941.961323,0.608896,327.505071,91.114710,34.246204
1,2003-01-02,10.484796,942.675433,3.006925,290.310937,91.934631,35.734294
2,2003-01-03,12.606104,942.881457,2.872020,279.921010,92.393007,32.590960
3,2003-01-04,12.646417,943.009227,2.678422,274.952584,92.312594,35.435619
4,2003-01-05,13.066706,943.762527,3.104962,275.257170,92.569458,34.235347
...,...,...,...,...,...,...,...
6553,2020-12-25,12.096190,941.053885,2.152634,261.457477,92.849653,33.209944
6554,2020-12-26,13.381471,942.263093,2.312996,253.686322,93.400294,31.352555
6555,2020-12-27,13.819016,941.287692,2.260313,252.095788,93.560516,33.862652
6556,2020-12-28,13.831078,940.630939,2.003774,254.229795,93.895661,32.318171
6557,2020-12-29,13.515426,940.271228,2.372698,272.744304,93.724668,34.509701

### Exporting the prepared data

In [743]:
os.makedirs('../Data/Processed', exist_ok=True)

In [744]:
blr_df.to_csv('../Data/Processed/blr_df.csv', index=False)
hyd_df.to_csv('../Data/Processed/hyd_df.csv', index=False)
pune_df.to_csv('../Data/Processed/pune_df.csv', index=False)