# Importing the Necessary Libraries

In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Loading the cleaned datasets

In [101]:
blr_df = pd.read_csv("../Data/Processed/blr_df.csv")
pune_df = pd.read_csv("../Data/Processed/pune_df.csv")
hyd_df = pd.read_csv("../Data/Processed/hyd_df.csv")

In [102]:
blr_df

,Date,DPT,AP,WS,WSD,RH,LST
0,2003-01-01,12.498648,916.589625,0.608896,327.505071,93.194473,30.939528
1,2003-01-02,12.825784,918.004624,3.006925,290.310937,93.578218,31.179113
2,2003-01-03,12.970981,918.453619,2.872020,279.921010,94.227231,33.045705
3,2003-01-04,12.445614,917.966755,2.678422,274.952584,93.297114,38.266933
4,2003-01-05,14.071074,918.579933,3.104962,275.257170,94.353249,33.185394
...,...,...,...,...,...,...,...
6553,2020-12-25,13.500707,916.151180,2.152634,261.457477,95.470006,32.118758
6554,2020-12-26,12.901577,917.194971,2.312996,253.686322,95.361429,32.068009
6555,2020-12-27,12.950693,916.302854,2.260313,252.095788,94.854902,34.539327
6556,2020-12-28,10.830827,916.237697,2.003774,254.229795,93.468912,31.310399
6557,2020-12-29,16.207934,915.751192,2.372698,272.744304,96.359538,32.945682

In [103]:
pune_df

,Date,DPT,AP,WS,WSD,RH,LST
0,2003-01-01,7.100958,941.961323,0.608896,327.505071,91.114710,34.246204
1,2003-01-02,10.484796,942.675433,3.006925,290.310937,91.934631,35.734294
2,2003-01-03,12.606104,942.881457,2.872020,279.921010,92.393007,32.590960
3,2003-01-04,12.646417,943.009227,2.678422,274.952584,92.312594,35.435619
4,2003-01-05,13.066706,943.762527,3.104962,275.257170,92.569458,34.235347
...,...,...,...,...,...,...,...
6553,2020-12-25,12.096190,941.053885,2.152634,261.457477,92.849653,33.209944
6554,2020-12-26,13.381471,942.263093,2.312996,253.686322,93.400294,31.352555
6555,2020-12-27,13.819016,941.287692,2.260313,252.095788,93.560516,33.862652
6556,2020-12-28,13.831078,940.630939,2.003774,254.229795,93.895661,32.318171
6557,2020-12-29,13.515426,940.271228,2.372698,272.744304,93.724668,34.509701

In [104]:
hyd_df

,Date,DPT,AP,WS,WSD,RH,LST
0,2003-01-01,9.801921,952.321702,2.702138,228.989644,91.137446,35.253027
1,2003-01-02,12.894156,953.896739,2.974241,287.669929,92.938629,31.660535
2,2003-01-03,16.945643,954.471306,3.015529,308.536731,96.690377,30.085849
3,2003-01-04,17.761199,954.172469,1.865083,299.395258,98.016959,30.569864
4,2003-01-05,14.281283,954.395644,2.287668,265.010524,93.245268,31.878895
...,...,...,...,...,...,...,...
6553,2020-12-25,13.330685,951.670802,2.015309,292.172202,94.673562,30.396700
6554,2020-12-26,14.027632,952.521458,1.736367,284.297801,94.788311,32.262344
6555,2020-12-27,13.223768,951.342613,1.754041,288.307250,94.039085,33.796627
6556,2020-12-28,12.504071,951.101661,2.012608,299.893708,93.248170,31.748070
6557,2020-12-29,12.890767,951.123203,2.545894,294.997468,93.764521,33.091597

## Converting them to datetime

In [105]:
blr_df['Date'] = pd.to_datetime(blr_df['Date'])
pune_df['Date'] = pd.to_datetime(pune_df['Date'])
hyd_df['Date'] = pd.to_datetime(hyd_df['Date'])

## Displaying Basic Statistics

In [106]:
def stats(df : pd.DataFrame) -> None:
    display(df.describe())
    display(df.info())

In [107]:
stats(blr_df)

,Date,DPT,AP,WS,WSD,RH,LST
count,6558,6558.000000,6558.000000,6558.000000,6558.000000,6558.000000,6558.000000
mean,2011-12-31 09:30:27.996340224,16.110325,914.310984,2.721997,184.507564,94.688921,33.650531
min,2003-01-01 00:00:00,-1.577635,904.032537,0.024306,0.339358,80.411559,8.663021
25%,2007-07-02 06:00:00,13.735859,912.559178,1.847537,89.878488,92.721910,30.059763
50%,2011-12-30 12:00:00,17.750807,914.196110,2.597877,201.766900,95.880121,32.945954
75%,2016-06-29 18:00:00,19.073083,916.042743,3.457254,274.139568,97.228436,36.854445
max,2020-12-29 00:00:00,21.722752,921.052138,7.683884,359.579988,99.829235,50.627039
std,NaN,3.981654,2.279828,1.292984,97.276029,3.358661,5.066399

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6558 entries, 0 to 6557
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6558 non-null   datetime64[ns]
 1   DPT     6558 non-null   float64
 2   AP      6558 non-null   float64
 3   WS      6558 non-null   float64
 4   WSD     6558 non-null   float64
 5   RH      6558 non-null   float64
 6   LST     6558 non-null   float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 358.8 KB

None

In [108]:
stats(pune_df)

,Date,DPT,AP,WS,WSD,RH,LST
count,6558,6558.000000,6558.000000,6558.000000,6558.000000,6558.000000,6558.000000
mean,2011-12-31 09:30:27.996340224,15.491213,938.329055,2.721997,184.507564,93.252105,36.902698
min,2003-01-01 00:00:00,-3.193784,925.802060,0.024306,0.339358,77.641108,7.248520
25%,2007-07-02 06:00:00,11.099360,935.918545,1.847537,89.878488,89.987409,31.972853
50%,2011-12-30 12:00:00,16.301439,938.587564,2.597877,201.766900,93.076967,35.432010
75%,2016-06-29 18:00:00,20.492695,940.966471,3.457254,274.139568,97.592068,41.825789
max,2020-12-29 00:00:00,22.786191,946.540669,7.683884,359.579988,99.401981,56.251654
std,NaN,5.227530,3.288479,1.292984,97.276029,4.227472,6.776509

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6558 entries, 0 to 6557
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6558 non-null   datetime64[ns]
 1   DPT     6558 non-null   float64
 2   AP      6558 non-null   float64
 3   WS      6558 non-null   float64
 4   WSD     6558 non-null   float64
 5   RH      6558 non-null   float64
 6   LST     6558 non-null   float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 358.8 KB

None

In [109]:
stats(hyd_df)

,Date,DPT,AP,WS,WSD,RH,LST
count,6558,6558.000000,6558.000000,6558.000000,6558.000000,6558.000000,6558.000000
mean,2011-12-31 09:30:27.996340224,16.263553,947.743474,2.717791,192.492032,92.946126,35.986712
min,2003-01-01 00:00:00,-2.061998,931.235993,0.066775,0.040960,78.748496,10.201014
25%,2007-07-02 06:00:00,12.619997,944.473266,1.733854,90.345572,89.986233,32.531167
50%,2011-12-30 12:00:00,17.176186,947.740114,2.328450,208.751509,93.582201,35.244611
75%,2016-06-29 18:00:00,20.526991,951.018043,3.420206,294.808751,96.473931,39.075508
max,2020-12-29 00:00:00,23.197597,957.054407,7.742450,359.992796,99.844393,53.419008
std,NaN,4.732127,3.863365,1.476708,104.550772,4.185125,4.969585

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6558 entries, 0 to 6557
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6558 non-null   datetime64[ns]
 1   DPT     6558 non-null   float64
 2   AP      6558 non-null   float64
 3   WS      6558 non-null   float64
 4   WSD     6558 non-null   float64
 5   RH      6558 non-null   float64
 6   LST     6558 non-null   float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 358.8 KB

None

# Exploratory Data Analysis

## Plotting a chart of time vs LST

In [110]:
def plotTimeVsLST(df: pd.DataFrame, city : str) -> None:
    """
    Plots an interactive Time vs LST chart using Plotly, with years shown on the x-axis.
    
    :param df: DataFrame containing 'Date' and 'LST' columns.
    """
    # Ensure 'Date' is datetime
    df['Date'] = pd.to_datetime(df['Date'])
    
    # Add 'Year' column
    df['Year'] = df['Date'].dt.year
    
    # Plot using Plotly
    fig = px.line(
        df,
        x='Date',
        y='LST',
        title=f'Date vs Land Surface Temperature (LST) for {city}',
        labels={'Date': 'Year', 'LST': 'Land Surface Temperature (°C)'},
        template='plotly_white'
    )
    
    # Customize x-axis to only show year ticks
    fig.update_layout(
        xaxis=dict(
            tickmode='array',
            tickvals=pd.date_range(start=df['Date'].min(), end=df['Date'].max(), freq='YS'),
            tickformat='%Y',
            tickangle=45
        ),
        title_font_size=20,
        font=dict(size=14),
        margin=dict(t=50, b=50, l=40, r=40),
        hovermode="x unified"
    )
    
    fig.update_traces(line=dict(width=2), marker=dict(size=4))
    fig.show()

In [111]:
plotTimeVsLST(blr_df, 'Bengaluru')

In [112]:
plotTimeVsLST(pune_df, 'Pune')

In [113]:
plotTimeVsLST(hyd_df, 'Hyderabad')

## Conclusions
1. As expected we do see a cyclical variation in LST over the years.

## Calculating the Pearson Correlation Coefficient and Visualizing it

In [114]:
def compute_pearson_correlation(df: pd.DataFrame, predictors: list) -> pd.DataFrame:
    """
    Computes the Pearson correlation coefficient of all columns in the DataFrame
    against the specified predictor variable(s).

    :param df: A pandas DataFrame with all numeric columns.
    :param predictors: A list of column names to use as predictors.
    :return: A DataFrame of Pearson correlation coefficients (rows: features, columns: predictors)
    """
    # Ensure predictor columns are in the DataFrame
    missing = [col for col in predictors if col not in df.columns]
    if missing:
        raise ValueError(f"Predictor columns not found in DataFrame: {missing}")

    # Only numeric columns
    numeric_df = df.select_dtypes(include='number')

    # Drop predictors from input features if they exist in the numeric set
    input_vars = [col for col in numeric_df.columns if col not in predictors]

    # Compute correlation matrix
    correlations = numeric_df[input_vars].corrwith(numeric_df[predictors[0]]).to_frame(name=predictors[0])
    
    for pred in predictors[1:]:
        correlations[pred] = numeric_df[input_vars].corrwith(numeric_df[pred])
    
    correlations.index.name = 'Input_Variables'
    return correlations

In [115]:
corr_coef_blr = compute_pearson_correlation(blr_df, ['LST'])
corr_coef_blr

                      LST
Input_Variables
DPT             -0.456401
AP               0.091355
WS              -0.282853
WSD              0.235207
RH              -0.722482
Year            -0.030432

In [116]:
corr_coef_pune = compute_pearson_correlation(pune_df, ['LST'])
corr_coef_pune

                      LST
Input_Variables
DPT             -0.403701
AP               0.100391
WS              -0.426278
WSD              0.207235
RH              -0.692997
Year            -0.099126

In [117]:
corr_coef_hyd = compute_pearson_correlation(hyd_df, ['LST'])
corr_coef_hyd

                      LST
Input_Variables
DPT             -0.320128
AP              -0.122507
WS              -0.263989
WSD              0.050881
RH              -0.674330
Year            -0.039032

In [118]:
corr_combined = pd.concat([corr_coef_blr, corr_coef_pune, corr_coef_hyd], axis=1)
corr_combined.columns = ['Bengaluru', 'Pune', 'Hyderabad']
corr_combined

                 Bengaluru      Pune  Hyderabad
Input_Variables
DPT              -0.456401 -0.403701  -0.320128
AP                0.091355  0.100391  -0.122507
WS               -0.282853 -0.426278  -0.263989
WSD               0.235207  0.207235   0.050881
RH               -0.722482 -0.692997  -0.674330
Year             -0.030432 -0.099126  -0.039032

In [121]:
corr_combined = corr_combined.drop(index='Year')
corr_combined

                 Bengaluru      Pune  Hyderabad
Input_Variables
DPT              -0.456401 -0.403701  -0.320128
AP                0.091355  0.100391  -0.122507
WS               -0.282853 -0.426278  -0.263989
WSD               0.235207  0.207235   0.050881
RH               -0.722482 -0.692997  -0.674330

In [122]:
def plot_correlation_heatmap(df: pd.DataFrame, title: str = "Correlation Heatmap") -> None:
    """
    Plots a large, well-spaced heatmap for the given DataFrame using Plotly.

    :param df: A pandas DataFrame where rows are input variables and columns are cities or categories.
    :param title: Title of the heatmap.
    """
    fig = px.imshow(
        df,
        text_auto=".2f",
        color_continuous_scale="RdBu_r",
        title=title,
        labels=dict(x="Cities", y="Input Variables", color="Correlation"),
        aspect="auto"
    )

    fig.update_layout(
        width=1200,
        height=800,
        title_font_size=28,
        font=dict(size=16),
        margin=dict(t=80, b=80, l=100, r=100),
        xaxis=dict(tickfont=dict(size=18)),
        yaxis=dict(tickfont=dict(size=18), autorange="reversed"),
    )

    fig.show()

In [123]:
plot_correlation_heatmap(corr_combined, title="Correlation Heatmap for Cities")